### ISSUE TITLE
What is the role of `out[:, :, -1]` and why the length of kernel should be equal to input data?

### ISSUE THREAD

**Issue by Kziqian** [dwromero/ckconv#11]
Hello, I've found your work is impressive and still learning it. 

I have 2 questions about the code:
(1) In `seqImg_CKCNN`, the last layer is `out = self.finallyr(out[:, :, -1])`. It is kind of confusing, because if only the `out[:, :, -1]` is considered, the convolution operation has no effect and the computation is wasted. In this situation, `out[:, :, -1]` is the result of point-wise multiply of input (x) and kernel. What is the role of `out[:, :, -1]` ?

(2) Why the length of kernel should be equal to input data? We all know that the size of standard CNNs should be carefully designed, but the length of kernel in your work is fixed and equal to input data. Why does it work?

Best,
Kzq

**Comment by dwromero** [comment]
Hi Kziqian,

Please forgive me for my late answer. Somehow I forgot to mark the notification and it went by unnoticed. 

With regard to 1):

First let me explain why we take the last element. We take the last element for the prediction of the image in order to base the prediction on the last token observed. This is important because the model is causal (i.e., it cannot see information from the future on the sequence), and thus, predicting the number from say the middle token would be much more difficult. 

Instead of taking the last element, an alternative --which we use in [CCNNs](https://github.com/david-knigge/ccnn)-- is to use the mean. This takes into account all of the tokens up to a certain point (thus not breaking causality). 

It is true that `out[:, :, -1]` disregards some information. Note, however, that the operation that takes place before this indexing is a residual block. Since it stacks multiple convolutions, use normalization, etc., then it is not really the case that it is simply a point-wise multiply. 

If the operation before the indexing `out[:, :, -1]` was a convolution, you would be entirely right.

With regard to 2):

The intuition behind having long kernels is that it allows models to model long term dependencies at every layer (a bit like self-attention). The core of our paper is to show that actually having large kernels (if parameterized properly) is better than having very deep networks with carefully designed kernels. I would argue that the reason this works is exactly because we can model long term dependencies at every layer,  which is not really possible or compelling with the conventional parameterization of convolutional kernels (as independent weights at each position), because long kernels require veeery large models. Our parameterization does not suffer from that problem :) 

In follow up work, we also see that we can let the network learn how big the kernels need to be (see [FlexConv](https://arxiv.org/abs/2110.08059)). We have also show that CKConvs can lead to much better results in our [CCNN](https://arxiv.org/abs/2206.03398) paper.

Please let me know if you have any other questions :) 

Cheers,
David

**Comment by Kziqian** [comment]
Awsome!  Thank you for answering my questions！
