### ISSUE TITLE
Use of nn.Conv1d instead of nn.Linear

### ISSUE THREAD

**Issue by Linkerbrain** [dwromero/ckconv#9]
Hello,

Thank you for your really interesting work. I have a question about the initiation of the CKConv Kernel:
https://github.com/dwromero/ckconv/blob/d44c6441a98792477d6259368c210089bb33fe7a/ckconv/nn/linear.py#L14

In the code as I understand it, a 1 dimensional convolution with a kernel size of 1 is used for the Siren. Could you explain the difference of using this method instead of a regular MLP layer (using for example nn.Linear)?

**Comment by dwromero** [comment]
Hi @Linkerbrain ,

thank you for your question. 

Yes, of course!

In short, both a `nn.Linear` applied to each position and a `nn.Conv` with kernel size 1 are doing the same thing. The only thing that changes is the shape of the input going into `self.KernelNet`. I prefer using `nn.Conv` because this save us some permutation operations which would be required if we use `nn.Linear` in `self.KernelNet`, and then `nn.ConvNd` to compute the convolution between the input and the kernel generated.

A `nn.Linear` accepts inputs of dimensions `[batch_size, *, no_channels]`, and a conv layer accepts inputs of dimensions `[batch_size, no_channels, X]`. If we want to use `nn.Conv` to compute a convolution between the input signal (typically also defined as  `[batch_size, in_channels, X]` a kernel generated with `nn.Linears` of form `[batch_size, *, out_channels * in_channels]`, then we would need to permute the kernel before we can call the convolution. This is avoided by using `nn.Conv1d` in `self.KernelNet`. 

Cheers,
David
